/**
 * MCP Write Tools — Strike Output, Instruments, Capital Allocation, Loop Status
 *
 * Registers 6 write/generation MCP tools against the provided McpServer instance.
 * These tools invoke service layer functions and may write to Supabase.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { getSupabaseClient } from '@/lib/db/supabase';
import { validate, record, recordFailure } from '@/lib/capital/CapitalAllocationService';
import { generate as generateStrike } from '@/lib/strike/StrikeOutputEngine';
import { getById as getInstrumentById, getByYear } from '@/lib/instruments/InstrumentArchive';

/**
 * Registers all 6 write/generation tools on the given MCP server instance.
 */
export function registerWriteTools(server: McpServer): void {
  // ─── generate_strike_output ────────────────────────────────────────────────
  server.tool(
    'generate_strike_output',
    'Generates a complete 5-Part Strike Hierarchy output for the given OS Module slugs. ' +
      'Sections: Executive Analysis, OS Stress Test, The Imperial Instrument, ' +
      'Action Plan (T-Minus 24 Hours), The Ritual. ' +
      'Uses Claude 3.5 Sonnet with template fallback. Persists to Supabase.',
    {
      targetSlugs: z
        .array(z.string())
        .min(1)
        .describe('One or more OS Module slugs to target (e.g., ["TAX-OS", "KIRO-OS"])'),
      directive: z
        .string()
        .optional()
        .describe('Optional strategic directive or context for the generation'),
      userId: z
        .string()
        .optional()
        .describe('User ID for attribution (defaults to "mcp-agent")'),
    },
    async ({ targetSlugs, directive, userId = 'mcp-agent' }) => {
      try {
        const output = await generateStrike({ targetSlugs, directive, userId });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(output, null, 2) }],
        };
      } catch (err) {
        return {
          content: [{
            type: 'text' as const,
            text: `Error: STRIKE_GENERATION_FAILED — ${err instanceof Error ? err.message : 'Unknown error'}`,
          }],
          isError: true,
        };
      }
    }
  );

  // ─── get_instrument ────────────────────────────────────────────────────────
  server.tool(
    'get_instrument',
    'Returns the complete instrument document for a given DH-RES-YYYY-NNN identifier. ' +
      'Instruments are formal audit-ready documents generated by the Strike Output Engine.',
    { id: z.string().describe('Instrument identifier in format DH-RES-YYYY-NNN, e.g. "DH-RES-2026-001"') },
    async ({ id }) => {
      try {
        const instrument = await getInstrumentById(id);

        if (!instrument) {
          return {
            content: [{ type: 'text' as const, text: `Error: INSTRUMENT_NOT_FOUND — identifier "${id}" not in registry` }],
            isError: true,
          };
        }

        return {
          content: [{ type: 'text' as const, text: JSON.stringify(instrument, null, 2) }],
        };
      } catch (err) {
        return {
          content: [{
            type: 'text' as const,
            text: `Error: INSTRUMENT_ARCHIVE_UNAVAILABLE — ${err instanceof Error ? err.message : 'Unknown error'}`,
          }],
          isError: true,
        };
      }
    }
  );

  // ─── list_instruments ──────────────────────────────────────────────────────
  server.tool(
    'list_instruments',
    'Returns all instrument registry entries for a given calendar year, ordered by NNN ascending. ' +
      'Each entry includes the DH-RES identifier, title, issuing authority, generated timestamp, and status.',
    { year: z.number().int().min(2020).max(2100).describe('Calendar year, e.g. 2026') },
    async ({ year }) => {
      try {
        const entries = await getByYear(year);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(entries, null, 2) }],
        };
      } catch (err) {
        return {
          content: [{
            type: 'text' as const,
            text: `Error: INSTRUMENT_QUERY_FAILED — ${err instanceof Error ? err.message : 'Unknown error'}`,
          }],
          isError: true,
        };
      }
    }
  );

  // ─── get_capital_allocation ────────────────────────────────────────────────
  server.tool(
    'get_capital_allocation',
    'Returns the most recent approved capital allocation record from the Codex. ' +
      'The mandate is 40% growth, 40% operational, 20% reserve.',
    {},
    async () => {
      try {
        const client = getSupabaseClient();
        const { data, error } = await client
          .from('capital_allocations')
          .select('*')
          .order('approved_at', { ascending: false })
          .limit(1)
          .single();

        if (error?.code === 'PGRST116') {
          return {
            content: [{ type: 'text' as const, text: 'No capital allocation records found.' }],
          };
        }

        if (error) {
          return {
            content: [{ type: 'text' as const, text: `Error: DB_QUERY_FAILED — ${error.message}` }],
            isError: true,
          };
        }

        return {
          content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }],
        };
      } catch (err) {
        return {
          content: [{
            type: 'text' as const,
            text: `Error: CAPITAL_QUERY_FAILED — ${err instanceof Error ? err.message : 'Unknown error'}`,
          }],
          isError: true,
        };
      }
    }
  );

  // ─── submit_capital_allocation ─────────────────────────────────────────────
  server.tool(
    'submit_capital_allocation',
    'Validates and records a capital allocation decision against the 40/40/20 mandate. ' +
      'Tolerance: ±0.005 percentage points per category. ' +
      'Returns the approved record on success, or validation errors on failure.',
    {
      growthPercent: z.number().describe('Percentage allocated to growth investments (target: 40)'),
      operationalPercent: z.number().describe('Percentage allocated to operational infrastructure (target: 40)'),
      reservePercent: z.number().describe('Percentage allocated to reserve/contingency (target: 20)'),
      userId: z.string().describe('User ID of the approving user'),
      slug: z.string().describe('OS Module slug this allocation is associated with'),
    },
    async ({ growthPercent, operationalPercent, reservePercent, userId, slug }) => {
      const allocation = {
        growthPercent,
        operationalPercent,
        reservePercent,
        osModuleSlug: slug,
      };

      const errors = validate(allocation);

      if (errors.length > 0) {
        await recordFailure(allocation, userId, errors).catch(() => {});
        return {
          content: [{
            type: 'text' as const,
            text: JSON.stringify({
              status: 'rejected',
              code: 'CAPITAL_ALLOCATION_INVALID',
              errors,
            }, null, 2),
          }],
          isError: true,
        };
      }

      try {
        const allocationRecord = await record(allocation, userId, slug);
        return {
          content: [{
            type: 'text' as const,
            text: JSON.stringify({ status: 'approved', record: allocationRecord }, null, 2),
          }],
        };
      } catch (err) {
        return {
          content: [{
            type: 'text' as const,
            text: `Error: DB_INSERT_FAILED — ${err instanceof Error ? err.message : 'Unknown error'}`,
          }],
          isError: true,
        };
      }
    }
  );

  // ─── get_loop_status ───────────────────────────────────────────────────────
  server.tool(
    'get_loop_status',
    'Returns the most recent execution record for a given Recursive Loop ID. ' +
      'Includes trigger timestamp, matched condition, target slug, output action, and outcome.',
    { loopId: z.string().describe('The Recursive Loop ID') },
    async ({ loopId }) => {
      try {
        const client = getSupabaseClient();
        const { data, error } = await client
          .from('loop_execution_log')
          .select('*')
          .eq('loop_id', loopId)
          .order('triggered_at', { ascending: false })
          .limit(1)
          .single();

        if (error?.code === 'PGRST116') {
          return {
            content: [{ type: 'text' as const, text: `No execution records found for loop "${loopId}".` }],
          };
        }

        if (error) {
          return {
            content: [{ type: 'text' as const, text: `Error: DB_QUERY_FAILED — ${error.message}` }],
            isError: true,
          };
        }

        return {
          content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }],
        };
      } catch (err) {
        return {
          content: [{
            type: 'text' as const,
            text: `Error: LOOP_STATUS_UNAVAILABLE — ${err instanceof Error ? err.message : 'Unknown error'}`,
          }],
          isError: true,
        };
      }
    }
  );
}
