[Interface]
Address = 10.80.0.2/24
PrivateKey = sBKUkEkX5725zxvIA6AjsSqthfXprLcr1iU3fKYnBkI=
DNS = 1.1.1.1, 8.8.8.8

[Peer]
# VPS server
PublicKey = LPeRuGR953mqGsZqBcEHlbOp/pcPqGsy3IAG/c8dAE8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 2.28.6.68:51820
PersistentKeepalive = 25
